version: '3.6'
services:
  db:
    image: mariadb:10.5.4-focal
    container_name: db
    volumes:
      - ./cms/conf/mysql/data/:/var/lsib/mysql/:rw
      - ./cms/sql/:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_ROOT_PASSWORD=0nGf1nd3R4dm1n
      - MYSQL_USER=ongfinder
      - MYSQL_PASSWORD=0nGf1nd3R
      - MYSQL_DATABASE=ongfinder
    restart: always

  adminer:
    image: adminer:4.7.7-standalone
    container_name: adminer
    links:
      - db
    ports:
      - 8080:8080
    restart: always
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 3333:3333
    links:
      - db

      