version: '3.6'
services:
  db:
    image: postgres    
    environment:
      - POSTGRES_USER=ongfinder
      - POSTGRES_PASSWORD=0nGf1nd3R
    expose:
      - "5433"
    ports:
      - "5433"
    restart: always

  adminer:
    image: adminer        
    ports:
      - 8080:8080
    restart: always
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 3333:3333
    links:
      - db
    command: bash - c "sleep 10 && npm run knex migrate:latest --file knexfile.js"